apiVersion: v1
kind: Pod
metadata:
  name: my-init-pod
spec:
  initContainers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 20"]
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
